"""empty message

Revision ID: 8b0d6d725ca8
Revises: 
Create Date: 2023-10-15 10:41:03.707577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0d6d725ca8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactus',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_message', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('therapist',
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('theraname', sa.String(length=80), nullable=False),
    sa.Column('theraemail', sa.String(length=120), nullable=False),
    sa.Column('Therapassword', sa.String(length=255), nullable=False),
    sa.Column('thera_img', sa.String(length=120), nullable=True),
    sa.Column('registration_date2', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('specialization', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('therapist_id'),
    sa.UniqueConstraint('theraemail'),
    sa.UniqueConstraint('theraname')
    )
    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_img', sa.String(length=120), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('sender_avatar', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('therapist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist.therapist_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultation',
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_therapist', sa.Integer(), nullable=False),
    sa.Column('consultaion_text', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='pending', nullable=False),
    sa.Column('booking_time', sa.DateTime(), nullable=True),
    sa.Column('feedback', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_therapist'], ['therapist.therapist_id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('consultation_id')
    )
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('likes',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['post.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    op.create_table('response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('userpostid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('response_text', sa.String(length=500), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.userid'], ),
    sa.ForeignKeyConstraint(['userpostid'], ['post.post_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    op.drop_table('likes')
    op.drop_table('post')
    op.drop_table('consultation')
    op.drop_table('chat')
    op.drop_table('user')
    op.drop_table('therapist')
    op.drop_table('contactus')
    # ### end Alembic commands ###
