"""empty message

Revision ID: f5d78555f1b6
Revises: 4fdf418967a4
Create Date: 2023-10-17 15:18:45.406583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5d78555f1b6'
down_revision = '4fdf418967a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('likes_ibfk_3', type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('likes_ibfk_3', 'post', ['post_id'], ['post_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
